# Generated by Django 4.1.6 on 2023-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, upload_to='article/files', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='background',
            field=models.ImageField(blank=True, upload_to='article/images', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
